//What is time complexity?
// whenever we write a code we should know about its time and space complexity.....
//Time complexity is != time taken...... time complexity is the rate of which the time taken increases with respect to the input size